### PR TITLE
Improve vendoring script

### PR DESCRIPTION
**Pull request by aburgel**
/domain @Betterment/test_track_core 
/no-platform

1. Switch from bower to npm

2. Remove her/fakeable_her from script since the version that's pulled doesn't match what is already committed.

_update: removed the bit about adding the cli downloading, it was already there, i just bumped the version number_

### CODE REVIEW

**Comment by samandmoore** [comment]
> 2\. Remove her/fakeable_her from script since the version that's pulled doesn't match what is already committed.

so you're saying that we patched these gems in this repo manually or something so you're just giving up on updating them for now? i'm fine with that

**Comment by samandmoore** [comment]
<<domain tafn just wanna understand the gem thing

**Comment by aburgel** [comment]
> so you're saying that we patched these gems in this repo manually or something so you're just giving up on updating them for now? i'm fine with that

yeah, basically. as is, you have to back out the changes made by this script, so it makes it not useful for updating.

there may be some commit hash that maps to the version we're actually using, but i'm not sure what that is. given that our usage of those libraries is pretty stable, i don't think there's any value in trying to update to the latest versions. our best bet would be to rip these out and use something more modern for rest apis.

**Comment by aburgel** [comment]
bump

**Comment by samandmoore** [comment]
domainlgtm

**Pull request merged**
